articles/urls.py
from django.urls import path

from .views import (
    article_search_view,
    article_create_view,
    article_detail_view,
)

app_name = 'articles'

urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (login_view, logout_view , register_view)
from .views import home_view
from articles import views



urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls',namespace ='article')),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view)
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h3>HELLO THERE! THIS IS MY BLOG</h3>

<form action ='/articles' method ='GET'>
  <input type='text' name = 'q' />
  <input type ='submit'/>
</form>
  
  {% block content %}
  <H3>THIS WILL BE REPLACED</H3>
  {% endblock content %}
</body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.title }}  {{ id }}Create an article below!</h1>
<p>{{ content }}</p>

<a href='{% url "articles:create" %}'>Create Article</a>
<a href='{% url "articles:detail" slug="hello-world" %}'>Hello world article</a>
<p>{{ content }}These are some of my articles</p>
<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href='{{ x.get_absolute_url }}'>{{ x.title }} - {{ x.content }}</a></li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}