mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (login_view, logout_view , register_view)
from .views import home_view
from articles import views



urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls',namespace ='article')),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view)
]

recipes/urls.py
from django.urls import path

from .views import(
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view,
)

app_name = 'recipes'

urlpatterns = [
  path("", recipe_list_view, name='list'),
  path("create/", recipe_create_view, name='create'),
  path("<int:id>/edit/", recipe_update_view, name='update'),
  path("<int:id>/", recipe_detail_view, name='detail'),
]
  

recipes/models.py
import pint
from django.conf import settings
from django.db import models
from django.urls import reverse
from .utils import number_str_to_float
from .validators import validate_unit_of_measure

# Create your models here.
class Recipe(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  name = models.CharField(max_length=220)
  description = models.TextField(blank=True, null=True)
  directions = models.TextField(blank=True, null=True)
  timestamp = models.DateTimeField(auto_now_add=True) 
  updated = models.DateTimeField(auto_now=True) 
  active = models.BooleanField(default=True)

  def get_absolute_url(self):
    return reverse('recipes:detail', kwargs={'id': self.id})
    
  def get_edit_url(self):
    return reverse('recipes:update', kwargs={'id': self.id})
      
  def get_ingredients_children(self):
    return self.recipeingredient_set.all()


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50, blank=True, null=True)  
    quantity_as_float = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=50, validators=[validate_unit_of_measure], blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True)


    def get_absolute_url(self):
       return self.get_absolute_url()

    def save(self, *args, **kwargs):
      qty = self.quantity
      qty_as_float, qty_as_float_success = number_str_to_float(qty)
      if qty_as_float_success:
          self.quantity_as_float = qty_as_float
      else:
          self.quantity_as_float = None
      super().save(*args, **kwargs)
    
    def convert_to_system(self, system="mks"):
      if self.quantity_as_float is None:
          return None
      ureg = pint.UnitRegistry(system=system)
      measurement = self.quantity_as_float * ureg[self.unit]
      return measurement #.to_base_units()
    
    def as_mks(self):
      # meter, kilogram, second
      measurement = self.convert_to_system(system='mks')
      return measurement.to_base_units()
    
    def as_imperial(self):
      # miles, pounds, seconds
      measurement = self.convert_to_system(system='imperial')
      return measurement.to_base_units()
  

recipes/forms.py
from django import forms

from .models import Recipe, RecipeIngredient

class RecipeForm(forms.ModelForm):
  # required_css_class = 'required-field'
  class Meta:
    model = Recipe
    fields = ['name', 'description', 'directions']


class RecipeIngredientForm(forms.ModelForm):
  class Meta:
    model = RecipeIngredient
    fields = ['name', 'quantity', 'unit']

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory
from django.shortcuts import redirect, render, get_object_or_404

from .forms import RecipeForm, RecipeIngredientForm
from .models import Recipe, RecipeIngredient 
# Create your views here.

@login_required
def recipe_list_view(request):
    qs = Recipe.objects.filter(user=request.user)
    context = {
        "object_list": qs
    }
    return render(request, "recipes/list.html", context)




@login_required
def recipe_detail_view(request, id=None):
  obj = get_object_or_404(Recipe, id=id, user=request.user)
  context = {
    'object':obj
            }
  return render(request, "recipes/detail.html", context)






@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
      obj = form.save(commit=False)
      obj.user = request.user
      obj.save()
      return redirect(obj.get_absolute_url())

    return render(request, "recipes/create-update.html", context)





@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance =obj)
    RecipeIngredientFormset = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=0)
    qs = obj.recipeingredient_set.all()
    formset = RecipeIngredientFormset(request.POST or None, queryset=qs)
    
    context = {
        "form": form,
        "formset": formset,
        "object": obj
    }
    if all([form.is_valid(), formset.is_valid()]):
        parent = form.save(commit=False)
        parent.save()
        for form in formset:
            child = form.save(commit=False)
            if child.recipe is None:
                print('added new')
                child.recipe = parent
            child.save()
        
        context['message'] = 'Data saved.'
    return render(request, "recipes/create-update.html", context)
  

templates/recipes/create-update.html
{% extends "base.html" %}


{% block content %}

{% if message %}
 <p>{{ message }}</p>
{% endif %}



<div style='margin-top:30px;'>
    <form action='.' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        
        {% if formset %}
        <h3>Ingredients</h3>
          {% for form in formset %}
            {{ form.as_p }} 
          {% endfor %}  
         
        {% endif %}
        <button style='margin-top:10px;' type='submit' >Save</button>
    </form>
</div>


{% endblock content %}

templates/recipes/detail.html
{% extends "base.html" %}


{% block content %}

<h1>{{ object.name }} {% if object.get_edit_url %}<small><a href ='{{ object.get_edit_url }}'>Edit</a></small>{% endif %}</h1>
<p>{{ object.description }}</p>
<p>{{ object.directions }}</p>

{% for ingredient in object.get_ingredients_children %}
<h1>{{ ingredient.name }}</h1>
<p>{{ ingredient.as_imperial }}</p>
<p>{{ ingredient.as_mks }}</p>
{% endfor %}
<!-- <div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class='htmx-indicator'>Loading...</div>
</div> -->

{% endblock content %}

templates/recipes/list.html
<h1>You are in the recipe part of the blog</h1>
<!-- will be fairly plain for now -->


{% extends "base.html" %}

{% block content %}
<h1>My Recipes</h1>
<h3><a href='{% url "recipes:create" %}'>Add Your Recipe</a></h3>
<hr/>
<ul>
    {% for x in object_list %}
       <li><a href='{{ x.get_absolute_url }}'>{{x.name}}</a></li> 
    {% empty %}
       <li>No recipes found.</li>
    {% endfor %}
</ul>

{% endblock content %}

<!-- <div class='mb-3'>
        <a class='lead' href='{{ x.get_absolute_url }}'>{{ x.name }}</a>
        <div hx-get='{% url "meal-toggle" recipe_id=x.id %}' hx-trigger='revealed'></div>
</div> -->